services:
  api:
    build: 
      context: ../sever
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: api-sv
    environment:
      - ORIGIN_CORS = http://localhost
    networks:
      - social-net
    expose:
      - 4000
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    networks:
      - social-net
    volumes:
      - ../client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  social-net:
    driver: bridge

