services:
  api:
    build: 
      context: ../sever
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: api-sv-social
    environment:
      -  ORIGIN_CORS_SSL=https://space-social.online
    networks:
      - social-net
    expose:
      - 5000
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8081:80
    networks:
      - social-net
    volumes:
      - ../client/build:/usr/share/nginx/space
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  social-net:
    driver: bridge

