services:
  api:
    build: 
      context: ../sever
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: api-sv-social-container
    environment:
      -  ORIGIN_CORS_SSL=http://space-social.online
    networks:
      - social-net-1
    expose:
      - 5000
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 81:80
    networks:
      - social-net-1
    volumes:
      - ../client/build:/var/www/space
      - ./default.conf:/etc/nginx/sites-available/space
networks:
  social-net-1:
    driver: bridge

